refactor: search w/o context and custom tab
questionpy-org/moodle-qtype_questionpy pull request #107
Opened 2024-03-25 15:35 UTC by janbritz

Closes #106.

Zum Suchen von Paketen wird nun grundsätzlich keine `contextid` mehr benötigt - außer bei der `recentlyused`-Kategorie. Alle hochgeladenen Pakete können von jedem Kontext aus gefunden werden.

Wie besprochen, gibt es nun statt der `Mine`-Kategorie die `Custom`-Kategorie (s. #106). Ich fände es nutzerfreundlicher, wenn die Kategorie nur Pakete anzeigt, die man selbst hochgeladen hat (dann wäre natürlich die Rückbenennung in `Mine` sinnvoll), da man womöglich kaum explizit nach `Custom`-Paketen suchen möchte. Falls das der Fall sein sollte, können die Pakete immernoch unter `All` gefunden werden.

Zusätzlich zu `ismine` wird nun auch das Feld `istrusted` für jede Paketversion zurückgegeben. Dieses Feld ist `true`, wenn die Paketversion auch vom Application-Server angeboten wird und kann genutzt werden, um lokale Paketversionen gesondert zu markieren.

Zuvor wurden Paketversionen, welche von mehreren Quellen (Usern/Application Server) hochgeladen wurden, mehrmals zurückgegeben - das ist nun gefixed.

2024-03-25 17:34 UTC, larsbonczek requested changes
Ich hatte es im letzten Meeting so verstanden, dass unter "custom" alle Paketversionen angezeigt werden sollen, die von mir oder von anderen Nutzer*innen _in einem Kontext, auf den ich Zugriff habe_ hochgeladen wurden. Jetzt gibst du ja einfach alle nutzerdefinierten Pakete zurück, oder?

Du könntest bei der Gelegenheit auch mal die Suchfunktion in eine eigene Klasse refaktorisieren, damit man sie theoretisch auch aus dem PHP-Code heraus benutzen kann und nicht nur als external service.

2024-03-25 17:34 UTC, larsbonczek commented on classes/external/favourite_package.php
> +        if ($exists = $DB->record_exists('qtype_questionpy_pkgversion', ['packageid' => $params['packageid']])) {
Muss nicht eigentlich überprüft werden, ob der User das Paket in irgendeinem Kontext sehen kann?

2024-03-25 17:34 UTC, larsbonczek commented on classes/package/package_version.php
> +        [$joinsql, $joinparams] = self::sql_get('s2.id IS NOT NULL');
Hier den Alias s2 so als magic value zu verwenden finde ich riskant. In jedem Fall wäre es gut, wenn in dem docstring von sql_get dokumentiert ist, welche Felder/Aliase verfügbar sind. Vor allem, da die Funktion public ist.

2024-03-25 17:34 UTC, larsbonczek commented on classes/package/package_version.php
> +                throw new moodle_exception('');
Bitte hier einen gültigen errorcode angeben (für den ein string existiert). Es gibt zum Beispiel "nopermissions". Aber ein eigener string wäre besser.

2024-03-25 17:34 UTC, larsbonczek commented on classes/package/package_version.php
> +    public static function sql_get(string $where = '', array $params = []): array {
Im Grunde könntest du hier auch direkt den Query ausführen und die Ergebnisse casten, oder? Ich würde dann vorschlagen, dass du eine Funktion `get_many_where: array` und eine Funktion `get_where: ?package_version`  anbietest, die du dann in den anderen Funktionen aufrufst.

2024-03-25 17:34 UTC, larsbonczek commented on classes/external/search_packages.php
> +            self::validate_context(context::instance_by_id($params['contextid'], IGNORE_MISSING));
Wieso IGNORE_MISSING? Macht hier keinen Unterschied, weil validate_context auch nen Fehler wirft wenn der Context leer ist. Aber dann kannst du es auch weglassen.

2024-03-25 17:34 UTC, larsbonczek commented on classes/external/remove_packages.php
>          $transaction = $DB->start_delegated_transaction();
Hier fehlt noch ein validate_context und eine Überprüfung der Berechtigung, oder nicht??

2024-03-25 17:34 UTC, larsbonczek commented on classes/external/load_packages.php
>          $transaction = $DB->start_delegated_transaction();
Hier fehlt noch ein validate_context und eine Überprüfung der Berechtigung, oder nicht??

2024-03-25 17:34 UTC, larsbonczek commented on db/install.xml
>          <FIELD NAME="userid" TYPE="int" LENGTH="10" NOTNULL="false" SEQUENCE="false"/>
Ich finde es ein bisschen unsauber hier das userid Feld einfach auf null zu setzen um zu signalisieren, dass die Paketversion vom Server kommt. Mein Vorschlag wäre, das als Boolean-Flag zu speichern entweder in einem qtype_questionpy_source Datensatz oder direkt in der Paketversion.

2024-03-26 11:40 UTC, janbritz commented
Antwort auf [deinen Kommentar](https://github.com/questionpy-org/moodle-qtype_questionpy/pull/107#pullrequestreview-1958213249) @larsbonczek. (Leider kann man ja nicht direkt antworten.)
> [...] unter "custom" alle Paketversionen angezeigt werden sollen, die von mir oder von anderen Nutzer*innen _in einem Kontext, auf den ich Zugriff habe_ hochgeladen wurden. [...]

Ich habe es so verstanden, dass alle lokalen Pakete unter "Custom" zu finden sein sollen, da mit dem zitierten Ansatz das Problem, welches ich beim letzten Meeting angesprochen habe, bestehen bleibt:

Person X hat Zugriff auf die Kurse A und B und lädt im Kurs A ein Paket hoch.
Person Y hat auch Zugriff auf die Kurse A und B.
Person Z hat nur Zugriff auf den Kurs B und kann damit, im Gegensatz zu Person X und Y, das Paket nicht finden - Person X müsste das Paket also auch im Kurs B wieder hochladen und das ist nicht gewollt.

2024-03-26 11:57 UTC, janbritz commented on classes/external/search_packages.php
> +            self::validate_context(context::instance_by_id($params['contextid'], IGNORE_MISSING));
[Hier](https://github.com/questionpy-org/moodle-qtype_questionpy/pull/74#discussion_r1416950428) ist meine damalige Begründung.

2024-03-26 12:02 UTC, janbritz commented on classes/external/remove_packages.php
>          $transaction = $DB->start_delegated_transaction();
Ja, allerdings sollen die Services nicht Teil des Production-Codes werden.

2024-03-26 12:03 UTC, janbritz commented on classes/external/load_packages.php
>          $transaction = $DB->start_delegated_transaction();
https://github.com/questionpy-org/moodle-qtype_questionpy/pull/107#discussion_r1539091287

2024-06-06 11:03 UTC, closed without merging