feat: remove custom tab but enable package upload
questionpy-org/moodle-qtype_questionpy pull request #108
Opened 2024-04-30 10:57 UTC by janbritz

![paket_auswahl](https://github.com/questionpy-org/moodle-qtype_questionpy/assets/43270252/71d8059c-0856-434b-a001-d904c4c90a35)

2024-05-16 13:34 UTC, MHajoha requested changes
* Ich glaube mir fehlen hier 1-2 Diskussionen, in denen Entscheidungen zu dem Zielverhalten getroffen wurden. Von daher kann ich nicht bewerten, ob das so korrekt ist oder ob es Missverständnisse wie in https://github.com/questionpy-org/moodle-qtype_questionpy/pull/107 gibt. Sieht aber für mich sinnvoll aus :+1: 
* Ich verliere langsam den Überblick, welche Form-Felder die Question wann hat, und wie sie auf Spalten in der `qtype_questionpy`-Tabelle mappen. Muss nicht sofort sein, aber eine Übersicht dazu wäre schön.
* Ich fände es noch wichtig, nach Auswahl/Hochladen eines Paketes bzw. beim Bearbeiten einer Frage leicht erkennen zu können, ob es ein lokales Paket ist oder nicht. Wenn ich mich nicht irre ist das gerade nur Anhand der An-/Abwesenheit des Favourite-Knopfes zu erschließen.

2024-05-16 13:34 UTC, MHajoha commented on templates/package/package_selection.mustache
>                      </div>
Lokale Pakete ohne URL kriegen jetzt ein leeres Dreipunktmenü:
![grafik](https://github.com/questionpy-org/moodle-qtype_questionpy/assets/29020266/b983cd46-edba-4719-94a6-2e0a3db670dc)

2024-05-16 13:34 UTC, MHajoha commented on classes/package_service.php
> +class package_service {
Schön zu sehen, dass ein paar Zeilen meines alten Anlaufs überlebt haben, allerdings müsste noch etwas aufgeräumt werden:
* `$api` wird nicht mehr benutzt
* Die PHPdocs der Klasse und von `get_file` treffen es nicht ganz
* In der Form könnte man auch den Namen präzisieren, z.B. `package_file_service`

2024-05-16 13:34 UTC, MHajoha commented on templates/package/package_selection.mustache
> +                            <a class="dropdown-item" href="#" data-for="favourite-button" {{#isfavourite}} data-is-favourite {{/isfavourite}}>
Warum eigentlich `for`?

2024-05-16 13:34 UTC, MHajoha commented on classes/external/favourite_package.php
> +        self::validate_context(context_system::instance());
Ich verstehe nicht 100%if, was `validate_context` macht, aber wäre der User-Context nicht sinnvoller? 

> To do so you should call the validate_context() function, passing the most specific context for the data.

2024-05-16 13:34 UTC, MHajoha commented on classes/api/api.php
>      }
Ich halte die `package_api`-Abstraktion nach wie vor für halbwegs sinnvoll, aber @MartinGauk hatte sich auf meinem PR damals dagegen ausgesprochen: <https://github.com/questionpy-org/moodle-qtype_questionpy/pull/32#issuecomment-1554379863>

2024-05-16 13:34 UTC, MHajoha commented on classes/question_service.php
> +                    "No package versiotsetn record with ID '{$record->pkgversionid}' was found despite being referenced" .
:)

2024-05-16 13:34 UTC, MHajoha commented on edit_questionpy_form.php
> +        $mform->setType('qpy_package_selected', PARAM_BOOL);
Wäre `qpy_package_changed` hier nicht weiterhin ein passenderer Name oder hat sich geändert, was dieser hidden input macht?

2024-05-16 13:34 UTC, MHajoha commented on edit_questionpy_form.php
> +        }
Das scheint nicht so sauber zu funktionieren. Wenn ich eine neue Frage erstellen will und kein Paket auswähle (1) bzw. keines Hochlade (2), erhalte ich unschöne Fehlermeldungen statt den hinweis, dass da was required ist.

(1): `Exception - qtype_questionpy\package\package::get_by_version(): Argument #1 ($pkgversionid) must be of type int, null given, called in [dirroot]/question/type/questionpy/edit_questionpy_form.php on line 191`

(2): `Coding error detected, it must be fixed by a programmer: draft file with id '298790094' does not exist`

2024-05-16 13:34 UTC, MHajoha commented on classes/package_service.php
> +    public function get_file(int $qpyid, int $contextid): stored_file {
Hier bitte insb. klarstellen, dass es anscheinend die ID des qtype_questionpy-Records ist, nicht des Packages o.ä.

2024-05-16 13:42 UTC, MHajoha commented
Der "Recently USed"-Knopf ist noch Out-of-Scope, korrekt? Weil der scheint seinen Job noch nicht zu tun

2024-05-27 13:55 UTC, janbritz commented on edit_questionpy_form.php
> +        $mform->setType('qpy_package_selected', PARAM_BOOL);
Es hat sich leicht verändert: `qpy_package_selected` ist jetzt `true` wenn ein Paket ausgewählt/hochgeladen wurde und `false`, wenn ein Paket bereits ausgewählt war und auf `Change` gedrückt wurde.

2024-05-29 13:06 UTC, janbritz commented on templates/package/package_selection.mustache
> +                            <a class="dropdown-item" href="#" data-for="favourite-button" {{#isfavourite}} data-is-favourite {{/isfavourite}}>
Meinst du die Begrifflichkeit? Ich hatte es so von Lars (Comment API) übernommen, find ich eigentlich okay so. `data-action` wäre aber z.B. auch passend.

2024-05-29 13:09 UTC, janbritz commented on classes/external/favourite_package.php
> +        self::validate_context(context_system::instance());
Das sollte in diesem Fall egal ist, da die Daten (Pakete) von jedem Kontext aus favorisiert werden können.

2024-06-12 16:15 UTC, MartinGauk approved these changes

2024-06-12 16:15 UTC, merged