feat: Recently-Used-Funktionalität
questionpy-org/moodle-qtype_questionpy pull request #111
Opened 2024-06-06 15:42 UTC by janbritz

Nach dem Speichern einer Frage wird ein Eintrag in die `qtype_questionpy_lastused`-Tabelle mit der aktuellen Zeit gemacht. Sollte in diesem Kontext bereits genau das Paket (die Version ist egal) ausgewählt worden sein, so wird nur der Zeitstempel aktualisiert.

2024-06-20 11:39 UTC, MHajoha approved these changes
Das hat jetzt allerdings eine Wechselwirkung mit `\qtype_questionpy\external\load_packages`: Dort werden erst alle Pakete gelöscht und danach alle neu vom Server geholten erstellt. Vorher war das kein Problem, jetzt fliegen aber die `last_used`-Einträge mit raus. 

D.h. selbst wenn ich nur neue Pakete zum Server hinzufüge, setzt "Load Packages" den "Recently Used"-Tab zurück.

2024-06-20 12:36 UTC, larsbonczek requested changes
Ich persönlich empfinde den `last_used_service` so wie er gerade ist als overkill. Brauchen wir dafür eine eigene Klasse? Oder wird da noch viel Code dazu kommen?

2024-06-20 12:36 UTC, larsbonczek commented on classes/last_used_service.php
> +    const TABLE_NAME = 'qtype_questionpy_lastused';
Für Namen von DB-Objekten (Tabellen, Spalten) bitte keine Konstanten verwenden. Wir betrachten die als "Code", also können sie immer ausgeschrieben werden. Nur wenn du abstrakte Funktionen entwickelst, die auf verschiedenen Tabellen arbeiten können, ist das sinnvoll.

2024-06-20 12:36 UTC, larsbonczek commented on tests/last_used_service_test.php
> +    private const TABLE_NAME = last_used_service::TABLE_NAME;
Auch hier bitte keine Konstante verwenden.

2024-06-20 12:36 UTC, larsbonczek commented on db/install.xml
> +        <KEY NAME="contextid_packageid" TYPE="unique" FIELDS="contextid, packageid"/>
Ich glaube das hier sollte ein Index sein und `contextid-packageid` heißen.

> Key and index names under the XMLDB Files must be formed by concatenating the name of the fields present in the key/index with the '"-" (minus) character.
> [...]
> Declare any fields as UNIQUE KEY (UK) only if they are going to be used as target for one FK. Create unique indexes instead.

https://docs.moodle.org/dev/XMLDB_defining_an_XML_structure#Conventions

2024-06-25 08:58 UTC, janbritz commented
@larsbonczek Es sollte noch mindestens die Methode `remove_by_context` und vllt. als "Admin-Funktion" `remove_by_context_and_package`, um z.B. ein bestimmtes Paket nicht mehr im Recently-Used-Tab anzuzeigen, hinzukommen.

2024-06-26 10:13 UTC, larsbonczek approved these changes

2024-06-27 13:26 UTC, merged