Such-Container: Filtern mit Tags
questionpy-org/moodle-qtype_questionpy pull request #116
Opened 2024-07-02 07:50 UTC by janbritz

Mit diesem PR können Pakete nach ihren Tags gefiltert werden.

![tags_auswahl](https://github.com/questionpy-org/moodle-qtype_questionpy/assets/43270252/58082300-0235-4f94-8e65-1eb519ca8fad)

Der Input und die Vorschläge bei der Tag-Suche haben folgende Eigenschaften:
1. Tags die mit der Query beginnen werden ganz oben angezeigt.
2. Häufiger existierende Tags erscheinen weiter oben in den Vorschlägen, ansonsten wird alphabetisch sortiert.
3. Sollte die Query leer sein, werden alle verfügbaren Tags angezeigt, wobei wie in Punkt 2 sortiert wird.

2024-07-09 10:35 UTC, janbritz commented on amd/src/package_search/mutations.js
> +        await this.searchPackages(stateManager, {tags: tags});
Ähnlich wie bei `searchPackagesByQuery` wollen wir auch hier die Seitenzahl zurücksetzen.

2024-07-16 13:27 UTC, larsbonczek requested changes

2024-07-16 13:27 UTC, larsbonczek commented on amd/src/package_search/components/tag_bar.js
> +        );
Ich denke das gehört eher in stateReady, oder nicht?

2024-07-16 13:27 UTC, larsbonczek commented on amd/src/package_search/components/tag_bar.js
> +};
Das würde ich in ein eigenes Modul verschieben, damit dieses Modul so wie die anderen Komponenten nur eine Klasse exportiert.

2024-07-16 13:27 UTC, larsbonczek commented on classes/external/get_tags.php
> + * This service localised package tags.
```suggestion
 * This service returns localised package tags.
```

2024-07-16 13:27 UTC, larsbonczek commented on classes/external/get_tags.php
> +            SELECT t.*, COUNT(pt.tagid) AS usage_count
Sollte die Anzahl an Verwendungen vielleicht im Tag-Datensatz gespeichert werden? Dann muss hier nicht jedes Mal gezählt werden.

2024-07-16 13:27 UTC, larsbonczek commented on classes/external/get_tags.php
> +        ", $sqlparams);
Wie viele Tags wird es ca. geben? Wäre hier vielleicht ein $limitnum sinnvoll?

2024-07-16 13:27 UTC, larsbonczek commented on classes/external/search_packages.php
> +            ) = $count
Bitte für $count einen Parameter verwenden.

2024-07-16 13:27 UTC, larsbonczek commented on classes/external/search_packages.php
> +        }
Das geht kompakter mit array_filter und implode (nicht getestet):
```suggestion
        $where = implode(') AND (', array_filter($clauses, 'strlen'));
        if ($where !== '') {
            $where = "WHERE ($where)";
        }
```

2024-07-16 13:27 UTC, larsbonczek commented on classes/package/package.php
> +                WHERE pt.packageid = :packageid
Mit diesem WHERE Filter zählt dein GROUP BY und COUNT nur die Zahl von Zuordnungen von diesem Tag zu diesem Paket - ist die nicht immer 1?

Einfacher wäre es, zuerst die Einträge aus qtype_questionpy_pkgtag zu löschen und danach alle Tags zu löschen, für die es keinen Eintrag in qtype_questionpy_pkgtag gibt.

2024-07-16 13:27 UTC, larsbonczek commented on classes/package/package_version.php
> +        $DB->delete_records('qtype_questionpy_pkgtag', ['packageid' => $this->packageid]);
Siehe Kommentar in package.php

2024-07-16 13:27 UTC, larsbonczek commented on db/install.xml
> +    </TABLE>
Man könnte überlegen noch einen Suchindex für das Feld tag hinzuzufügen. Dann würde zumindest der startswith Operator schneller funktionieren.

2024-07-16 13:27 UTC, larsbonczek commented on templates/package_search/tag_bar/input.mustache
> +{{/js}}
Wie besprochen, diese Datei bitte nicht duplizieren

2024-07-16 13:27 UTC, larsbonczek commented on templates/package_search/tag_bar/selection.mustache
> +    }} class="qpy-tag-bar-selection {{#multiple}}form-autocomplete-multiple{{/multiple}}"{{!
Wie besprochen, {{#multiple}} ist immer true

2024-07-16 13:27 UTC, larsbonczek commented on tests/package/package_test.php
Füge hier bitte noch einen Test mit zwei verschiedenen Paketen hinzu, wo zuerst eins gelöscht wird und dann das andere.

2024-07-17 15:34 UTC, janbritz commented on classes/external/get_tags.php
> +        ", $sqlparams);
Definitiv!

2024-07-17 15:43 UTC, janbritz commented on classes/external/get_tags.php
> +            SELECT t.*, COUNT(pt.tagid) AS usage_count
Daran hatte ich auch gedacht, allerdings sollte das auf die Performance bezogen, kaum einen Unterschied machen.

2024-07-22 14:26 UTC, larsbonczek requested changes
Einen Typo habe ich noch gefunden. Lief der Test trotzdem durch?

Wenn das gefixt ist und die Tests durchlaufen, kannst du gerne direkt mergen.

2024-07-22 14:26 UTC, larsbonczek commented on tests/package/package_test.php
> +        $package2 = package_provider(['namepsace' => 'ns2', 'tags' => ['b', 'c']])->store();
```suggestion
        $package2 = package_provider(['namespace' => 'ns2', 'tags' => ['b', 'c']])->store();
```

2024-07-22 16:15 UTC, janbritz commented on tests/package/package_test.php
> +        $package2 = package_provider(['namepsace' => 'ns2', 'tags' => ['b', 'c']])->store();
Ja, der Test lief trotzdem durch, da stattdessen der default namespace `my_namespace` verwendet wurde.

2024-07-22 16:28 UTC, merged