#119: Statische Dateien ausliefern
questionpy-org/moodle-qtype_questionpy pull request #125
Opened 2024-08-12 17:12 UTC by MHajoha

Ich hatte mir ursprünglich in den Kopf gesetzt, den ganzen Pfad von `file_pluginfile` bis inkl. `send_file` zu testen. Nach viel Zeitverschwendung bin ich aber zu dem Schluss gekommen, dass das nicht geht. U.a. geht Moodle davon aus, dass `qtype_questionpy_pluginfile` bei Erfolg immer `die`d, das lässt  sich auch für Tests nicht unterbinden. Und `send_file` macht alle Level von Output Buffering aus.

Zwei neue Dinge, die hier hinzukommen, sind die Nutzung des HTTP-Clients Guzzle und Moodle's Wrapper dafür, und Dependency Injection via <https://moodledev.io/docs/4.4/apis/core/di>. Den Rest des API-Codes sollten wir demnächst :tm: dann auch auf Guzzle umbiegen.

~~Aktuell scheitern die Actions beim Versuch, moodle-plugin-ci zu installieren. Das schaue ich mir morgen mal an, passiert aber auch auf dev.~~

2024-08-20 12:17 UTC, janbritz approved these changes

2024-08-20 12:17 UTC, janbritz commented on classes/api/package_api.php
> +            }
Da wir die Fehlermeldung nicht brauchen, ginge hier auch direkt:
```suggestion
            $json = json_decode($e->getResponse()->getBody(), associative: true);
            if (JSON_ERROR_NONE !== json_last_error()) {
                // Not valid JSON, so the problem probably isn't a missing package file.
                throw $e;
            }
```

2024-08-20 13:14 UTC, janbritz requested changes

2024-08-20 13:14 UTC, janbritz commented on classes/question_ui_renderer.php
> +            ";qpy://static(/(?:[a-z_][a-z0-9_]{1,127}){2}(?:/[\w\-@:%+.~=]+)+);",
```suggestion
            ";qpy://static(/(?:[a-z_][a-z0-9_]{0,126}){2}(?:/[\w\-@:%+.~=]+)+);",
```

2024-08-30 15:11 UTC, MartinGauk requested changes

2024-08-30 15:11 UTC, MartinGauk commented on classes/question_ui_renderer.php
> +            ";qpy://static(/(?:[a-z_][a-z0-9_]{1,127}){2}(?:/[\w\-@:%+.~=]+)+);",
Im SDK versuchen wir den hinteren Teil (Pfad) nicht zu matchen. In einem unserer Meetings hatten wir uns überlegt, dass das eigentlich keinen Vorteil bringt. Ist das hier notwendig?
Auf regex101.com matcht der Regex nicht. Der Schrägstrich muss verschoben werden: `;qpy://static((?:/[a-z_]`

2024-09-03 14:43 UTC, MHajoha commented on classes/question_ui_renderer.php
> +            ";qpy://static(/(?:[a-z_][a-z0-9_]{1,127}){2}(?:/[\w\-@:%+.~=]+)+);",
> Im SDK versuchen wir den hinteren Teil (Pfad) nicht zu matchen. In einem unserer Meetings hatten wir uns überlegt, dass das eigentlich keinen Vorteil bringt. Ist das hier notwendig?

Ich verwende hier halt `\moodle_url::make_pluginfile_url`, die den ganzen Pfad will. Es scheint zwar so, als würde das eigenhändige Zusammenstecken von `make_pluginfile_url(pathname: "", filename: "") . "$question->packagehash/$path"` oder so auch funktionieren, das ist aber denke ich nicht so gedacht und scheint mir brüchig.

> Auf regex101.com matcht der Regex nicht. Der Schrägstrich muss verschoben werden: `;qpy://static((?:/[a-z_]`

Stimmt :+1: (Wobei das eher dazu führen sollte, dass der Regex zusätzlich noch invalide URIs matcht)

2024-09-09 16:35 UTC, MartinGauk approved these changes

2024-09-11 12:55 UTC, janbritz approved these changes

2024-09-18 12:00 UTC, merged