Feature/8/package selection
questionpy-org/moodle-qtype_questionpy pull request #13
Opened 2022-07-28 08:07 UTC by janbritz

Closes #9, closes parts of #10.

Creates functionality to choose a QuestionPy package retrieved by the application server.

2022-07-28 13:13 UTC, MartinGauk requested changes

2022-07-28 13:13 UTC, MartinGauk commented on classes/api.php
> +}
Ich würde das eher als normale Klasse designen, d.h. im Objekt sind die URL, Timeout und später Zugangsdaten gespeichert, vielleicht auch das curlhandle.  Eine statische Funktion kann dann ein Objekt basierend auf der config instanziieren.
In Fehlerfällen würde ich auch mehr mit Exceptions arbeiten statt false zurückzugeben. Du kannst dafür eine `moodle_exception` werfen, musst dann aber in lang/en einen Text dazu definieren.

2022-07-28 13:13 UTC, MartinGauk commented on classes/api.php
> +        if (!filter_var($target, FILTER_VALIDATE_URL)) {
Ich denke, dass wir hier annehmen können, dass immer eine gültige URL rauskommt. Ansonsten wird sich curl schon beschweren. Im Prinzip sollte auch `PARAM_URL` in der `settings.php` bereits dafür sorgen, dass sich hinter `$serverurl` immer eine gültige URL befindet.

2022-07-28 13:13 UTC, MartinGauk commented on classes/api.php
> +    public static function get_packages() {
Hier wäre es schön, wenn eine Liste (array) an `package` Objekten zurückgegeben wird.

2022-07-28 13:13 UTC, MartinGauk commented on classes/package.php
> +        $newpackage['name'] = $package['name'][$selectedlanguage];
Du solltest vorbereitet sein, dass eventuell nicht in jedem Feld Übersetzungen zu allen Sprachen existieren, die in `$package['languages']` angegeben wurden.

2022-07-28 13:13 UTC, MartinGauk commented on classes/package.php
> +}
Hier sollte ein Objekt dieser Klasse genau ein Paket repräsentieren. Die möglichen properties sollten auch klar definiert sein (muss jetzt aber für den Anfang nicht vollständig sein). Die Objekte könnten dann von der Api-Klasse erzeugt werden und später auch von gespeicherten Daten aus der DB.

Ich würde vorschlagen, dass du eine helper Klasse erstellst mit einer statischen Funktion, die ein array zurückgibt. Das array gibt in absteigender Reihenfolge die Sprachen an, die der User haben will. Dabei können auch die parent languages berücksichtigt werden.
Die Rückgabe dieser Funktion könnte dann an `$package->get_localized_name/description($preferredlangs) : string` übergeben werden. Falls keine Übersetzung zu den gewünschten Sprachen existiert, kannst du ja wie oben die erste verfügbare Übersetzung zurückgeben.

Diese helper Funktion wird auch noch später relevant, weil dem Server ja je nach Route auch noch die gewünschten Sprachen des Users mitgeschickt werden.

2022-08-16 11:22 UTC, MHajoha approved these changes
Sieht schon super aus :+1:

Die Suche ist noch nicht implementiert und das gewählte Paket wird nicht in der DB abgespeichert, aber das ist vermutlich Absicht / out-of-scope, oder?

2022-08-16 11:22 UTC, MHajoha commented on classes/connector.php
> +class connector {
Anstatt hier selbst Abstraktionen um Curl herum zu bauen, können wir nicht vielleicht einen Http Client wie [Guzzle](https://docs.guzzlephp.org/en/stable/quickstart.html) benutzen?

2022-08-16 11:22 UTC, MHajoha commented on classes/localizer.php
> +    }
Gibt es einen Grund, dass diese Funktionen in einer Klasse sind? Ist das in PHP so üblich?

2022-08-16 11:22 UTC, MHajoha commented on classes/api.php
> +    }
Gibt es einen Grund, dass diese Funktionen in einer Klasse sind? Ist das in PHP so üblich?

2022-08-16 11:24 UTC, MHajoha approved these changes

2022-08-16 11:24 UTC, MHajoha commented on classes/package.php
> +    }
Moodle selbst verwendet keine Getter/Setter sondern greift direkt auf Felder zu. Falls nichts dagegen spricht, würde ich das auch bevorzugen.

2022-08-17 15:26 UTC, MHajoha commented on classes/connector.php
> +class connector {
On second thought: Da wir die QPPE API in einer OpenAPI spec definiert haben, können wir vermutlich auch zu https://openapi-generator.tech/docs/generators/php greifen, und uns einiges an code sparen.

Ich habe das mit `openapi-generator-cli generate -g php -o client -i ~/Work/questionpy-server/docs/qppe.yaml --invoker-package 'qtype_questionpy\\qppe_client'` mal ausprobiert und das Ergebnis sieht ganz sinvoll aus

2022-08-17 17:19 UTC, MartinGauk commented on classes/localizer.php
> +    }
Ich würde hier ausschließlich bei der Moodle-eigenen Funktion `get_parent_language` bleiben.

2022-08-17 17:19 UTC, MartinGauk commented on classes/localizer.php
> +        }
Auf diese Weise könnten zwar mehr Sprachen reinkommen, die passend für den User sein könnten. Mir wäre es aber lieber, wenn du hier die Moodle-eigene Funktion `current_language()` benutzt und die Logik nicht nachbaust, wo die Sprachen überall gespeichert sein können.

2022-08-17 17:19 UTC, MartinGauk commented on classes/api.php
> +    }
Zumindest in Moodle ist das so üblich, damit das Autoloading funktioniert.

2022-08-17 17:19 UTC, MartinGauk commented on classes/connector.php
> +class connector {
Zu Guzzle: Externe Abhängigkeiten sollten hier im Plugin vermieden werden. Eventuell könnte es noch sinnvoll sein, die Moodle-eigene `curl` Klasse zu verwenden, bin aber unsicher, wie viel die bringt.

2022-08-17 17:19 UTC, MartinGauk commented on classes/response.php
> +class response {
Den Namen bitte präzisieren. Response ist in diesem Plugin ein mehrdeutiger Begriff. ;)

2022-08-23 10:47 UTC, MHajoha commented on classes/connector.php
> +class connector {
Ich möchte halt vermeiden, das Rad neu zu erfinden. Inwiefern externe Dependencies möglich sind kommt sicherlich auf die gewollte Installationsmethode an. Da möchte ich Composer bzw. konkret den Typen `moodle-qtype` von https://github.com/composer/installers ins rennen werfen. Damit könnten wir ganz normal `composer require moodle-qtype-questionpy` (o.ä.) benutzen, unser Paket wird korrekt in `question/type/` installiert, und dessen Dependencies in `vendor/`.

2022-08-23 10:56 UTC, MHajoha commented on classes/connector.php
> +class connector {
Ich lese gerade https://docs.moodle.org/dev/Plugin_contribution_checklist#Dependencies

> Plugins must not require the admin to run composer or similar dependency manager tools. Many Moodle admins do not have access to their server shell and/or are not experienced with PHP building tools. Moodle plugins are supposed to be distributed in packages that work out of the box.

Das ist natürlich uncool, dann müssen wir wohl doch das Rad neu erfinden. (Oder Guzzle bundlen :thinking: )

2022-09-14 16:08 UTC, MartinGauk commented on classes/connector.php
> +            throw new moodle_exception(get_string('curl_init_error', 'qtype_questionpy'),
Bei der `moodle_exception` ist es eigentlich so gedacht, dass du als erstes Argument nur den lang key übergibst, also hier nur `'curl_init_error'`. Das 4. Argument steht dann durch den Platzhalter `{$a}` innerhalb der Übersetzung zur Verfügung.

Du müsstest das bitte an allen Stellen, an denen du eine `moodle_exception` wirfst, ändern.

2022-09-27 10:56 UTC, merged