refactor: update `qtype_questionpy` table
questionpy-org/moodle-qtype_questionpy pull request #130
Opened 2024-08-29 10:54 UTC by janbritz

Closes #129.

2024-08-29 15:33 UTC, MartinGauk requested changes
Mein Änderungswunsch rührte ja daher, dass die Fragen noch funktionieren sollen, selbst wenn die Paketinformationen in der DB gelöscht wurden, weil der Server temporärer bei einer Synchronisation keine Pakete zurückgibt. Bis zur nächsten Synchronisation können dann zwar keine Pakete für neue Fragen ausgewählt werden, aber die bestehenden Fragen müssen in jedem Fall weiterhin aufgerufen werden können, gerne auch noch bearbeitet werden können.

2024-08-29 15:33 UTC, MartinGauk commented on classes/question_service.php
> +            $package = package_version::get_by_hash($record->pkgversionhash);
Wir sollten auf die Überprüfung verzichten. Spätestens der Server meckert schon, wenn er das Paket nicht findet.

2024-08-29 15:33 UTC, MartinGauk commented on classes/question_service.php
> +                // TODO: retrieve the identifier directly from the package?
Wie meinst du das?

2024-09-12 12:55 UTC, janbritz commented on classes/question_service.php
> +                // TODO: retrieve the identifier directly from the package?
Der Identifier wird im Server generiert und könnte auch direkt mitgeliefert werden, falls es mal eine Änderung von `@{namespace}\{shortname}` geben sollte, müsste es nur dort angepasst werden.

2024-10-23 15:17 UTC, MartinGauk approved these changes

2024-10-23 15:29 UTC, merged