Feature/11/package persistence
questionpy-org/moodle-qtype_questionpy pull request #15
Opened 2022-08-25 15:06 UTC by alexanderschmitz

Ist vielleicht nicht die beste Lösung für neue features, aber ich habe einen neuen branch erstellt und branch 8 gemerged.

Neue Tabellen für: 
- localized data wie name, description, language
- tags

Man soll Packages aus #13  leichter speichern können.

2022-09-15 13:24 UTC, MartinGauk commented on db/install.xml
> +        <FIELD NAME="package_hash" TYPE="char" LENGTH="255" NOTNULL="true" SEQUENCE="false"/>
Verwende als Fremdschlüssel lieber `package_id`, also die `id` in der `qtype_questionpy_package` Tabelle. Auch unten in `qtype_questionpy_tags`.

2022-10-11 15:16 UTC, MHajoha requested changes

2022-10-11 15:16 UTC, MHajoha commented on classes/package.php
> +            $package[array_key_exists('short_name', $package) ? 'short_name' : 'shortname'],
Können wir die Namen der Spalten nicht an die aus dem JSON-Schema angleichen?

2022-10-11 15:16 UTC, MHajoha commented on db/install.xml
>          <FIELD NAME="questionid" TYPE="int" LENGTH="10" NOTNULL="true" DEFAULT="0" SEQUENCE="false"/>
D.h. wir speichern für jede Frage einzeln die Paketinformationen ab?
Würde es nicht mehr Sinn machen, jedes Paket nur max. einmal in eine separate Tabelle zu schreiben, und diese in `qtype_questionpy` zu referenzieren?
Dann bräuchten wir auch kein extra ID-Attribut, sondern könnten den Hash als PK verwenden. Konzeptionell ist er das ja.

2022-10-11 15:16 UTC, MHajoha commented on db/install.xml
> +        <FIELD NAME="language" TYPE="char" LENGTH="10" NOTNULL="true" SEQUENCE="false"/>
Kann Moodle's Datenbanklibrary zusammengesetzte PKs? Dann wäre hier vermutlich `(packageid, language)` angebracht.

Bei den Tags analog

2022-10-12 07:13 UTC, alexanderschmitz commented on classes/package.php
> +            $package[array_key_exists('short_name', $package) ? 'short_name' : 'shortname'],
Die Namen der Spalten müssen dem gleichen Schema folgen wie die Variablennamen in Moodle. Also lowercase und kein Underscore.

2022-10-12 07:20 UTC, alexanderschmitz commented on db/install.xml
> +        <FIELD NAME="language" TYPE="char" LENGTH="10" NOTNULL="true" SEQUENCE="false"/>
Leider nicht. 
"Every table must have an auto-incrementing id field (INT10) as primary key." [https://docs.moodle.org/dev/Database](url)

2022-10-12 07:36 UTC, alexanderschmitz commented on db/install.xml
>          <FIELD NAME="questionid" TYPE="int" LENGTH="10" NOTNULL="true" DEFAULT="0" SEQUENCE="false"/>
Ja das macht mehr Sinn.

2022-10-13 08:39 UTC, alexanderschmitz commented on db/install.xml
>          <FIELD NAME="questionid" TYPE="int" LENGTH="10" NOTNULL="true" DEFAULT="0" SEQUENCE="false"/>
4219652adc76f49ab01c89d4de83c14ff8bdd1eb
Die `qtype` Tabelle speichert jetzt den FK `questionid`. 
Vielleicht wollen wir in Zukunft noch eine Tabelle haben, die speichert welcher `context` auf welche packages Zugriff hat anstatt für jeden context die packages einzeln zu speichern.

2022-10-13 16:01 UTC, MHajoha commented on db/install.xml
>          <FIELD NAME="questionid" TYPE="int" LENGTH="10" NOTNULL="true" DEFAULT="0" SEQUENCE="false"/>
Ich verstehe noch nicht, warum ein Package überhaupt Contexts zugewiesen sein muss. Reicht es nicht, jedes Package einmal abzuspeichern und aus der Frage darauf zu verweisen?

2022-10-13 17:28 UTC, MartinGauk commented on db/install.xml
>          <FIELD NAME="questionid" TYPE="int" LENGTH="10" NOTNULL="true" DEFAULT="0" SEQUENCE="false"/>
Die Trainer sollen ja die Möglichkeit erhalten, eigene Pakete (innerhalb ihrer Kurse) hochzuladen. Diese Pakete müssen daher einem Kurs zugeordnet werden.

Für die Pakete, die der QPy-Server anbietet und allen zur Verfügung steht, wird der `context` später auf `CONTEXT_SYSTEM` gesetzt. Die kursbezogenen Pakete einem `CONTEXT_COURSE`.

2022-10-13 17:29 UTC, merged