Paket hochladen bei Frageerstellung
questionpy-org/moodle-qtype_questionpy pull request #32
Opened 2023-03-29 15:50 UTC by MHajoha

Noch nicht angegangen: Das Bearbeiten einer Frage, bei deren Erstellung ein Paket hochgeladen wurde. Ich denke dann sollte das hochgeladene Paket ganz oben in der Liste angezeigt werden. Momentan wird dann die Liste angezeigt, die aber immernoch nur Pakete enthält, die vom Server kommen.

Basiert auf #31

2023-04-14 09:38 UTC, janbritz approved these changes

2023-04-14 09:38 UTC, janbritz commented on lang/en/qtype_questionpy.php
> +$string['question_package_search'] = 'Select an existing packages';
```suggestion
$string['question_package_search'] = 'Select an existing package';
```

2023-04-14 09:38 UTC, janbritz commented on classes/package_service.php
> +     * * Ensures ensures that a database record exists for it
```suggestion
     * * Ensures that a database record exists for it
```

2023-04-14 09:38 UTC, janbritz commented on edit_questionpy_form.php
> +        $maxbytes = get_config('qtype_questionpy', 'applicationserver_maxquestionsize');
Wo findet man den Eintrag dazu?

2023-04-17 13:13 UTC, MHajoha commented on edit_questionpy_form.php
> +        $maxbytes = get_config('qtype_questionpy', 'applicationserver_maxquestionsize');
`applicationserver_maxquestionsize` hatte ich aus `qtype_questionpy\form\package_upload` übernommen, ist aber falsch. Der korrekte Eintrag heißt `max_package_size_kb` und ist in `settings.php` definiert. Gut, dass es dir auffällt :+1:

2023-04-24 17:04 UTC, MartinGauk requested changes
Mir fällt es ziemlich schwer, den Überblick zu behalten. Ich finde, dass das Formular dadurch zu kompliziert wird.

Wir sollten uns zunächst Gedanken machen, wie die Paketverwaltung für die Lehrenden eigentlich genau aussehen soll.

2023-04-24 17:04 UTC, MartinGauk commented on classes/api/package_api.php
> +                $filepath = $fs->get_file_system()->get_local_path_from_storedfile($this->file);
`get_local_path_from_hash` sollte mit `$fetchifnotfound = true` aufgerufen werden. Die Datei könnte in einem file storage liegen, das die Dateien nicht lokal speichert.

2023-04-24 17:04 UTC, MartinGauk commented on classes/api/api.php
> +        $filepath = $fs->get_file_system()->get_local_path_from_storedfile($file);
siehe oben

2023-04-24 17:04 UTC, MartinGauk commented on classes/package_service.php
> +        if ($packageid === null) {
Wenn eine Datei in einem anderen context neu hochgeladen wird, muss sie in dem anderen context erneut abgespeichert werden.

2023-04-24 17:10 UTC, MartinGauk commented on classes/package_service.php
> +                                         int         $contextid): stored_file {
Moodle bietet die Funktion `file_save_draft_area_files` an, um die Dateien aus der draft area zu speichern.

2023-04-28 12:39 UTC, MHajoha commented on classes/package_service.php
> +        if ($packageid === null) {
Mit der Datei müsste das ja schon so sein. Beim Package-DB-Eintrag bin ich mir unsicher, warum wir überhaupt eine contextid mit abspeichern. Reicht nicht ein Eintrag für alle Kontexte?

2023-04-28 13:03 UTC, MHajoha commented
> Mir fällt es ziemlich schwer, den Überblick zu behalten. Ich finde, dass das Formular dadurch zu kompliziert wird.
> 
> Wir sollten uns zunächst Gedanken machen, wie die Paketverwaltung für die Lehrenden eigentlich genau aussehen soll.

Meinst du der Code der Form ist zu kompliziert und sollte refactored werden oder die Form selbst ist für den Nutzer zu kompliziert und der Upload sollte woanders passieren?

Diese Variante bildet einen Use-Case sehr simpel (für die Nutzerin) ab, der denke ich ganz häufig sein könnte: Ein FG hat ihren Fragetypen für einen kommenden Test angepasst und lädt ihn beim Erstellen einer Frage hoch.

Vielleicht sollten wir auch eine Möglichkeit bauen, Fragepakete unabhängig von einer Frage hochzuladen / zu verwalten, aber das schließt sich ja nicht aus.

2023-05-19 10:42 UTC, MartinGauk commented
Dieser PR ist nach unserer Besprechung am Dienstag zur UI in weiten Teilen obsolet geworden.
@janbritz hat mich gefragt, ob er sich um das UI kümmern kann.

Der Commit bzgl. `max_package_size_kb` ist natürlich korrekt und den würde ich in den `dev` cherry-picken.
Die Änderungen bzgl. `connector::default()` sollten wir auch übernehmen. Hier müsstest du einen einzelnen Commit neu erstellen.

Die Auslagerung in die `package_api` finde ich eigentlich nicht notwendig. Die private `post_and_maybe_retry` Methode kann auch Teil von `api` sein. Im Hinblick auf #35 werden wir in der `api` auch eine allgemeine retry Methode benötigen, damit ggf. auf einen anderen Server ausgewichen werden kann, wenn einer gerade nicht erreichbar ist (oder wäre das eine Aufgabe von `connector`?).

2023-05-19 10:42 UTC, closed without merging