Refactor/package version handling
questionpy-org/moodle-qtype_questionpy pull request #45
Opened 2023-07-10 11:44 UTC by janbritz

Die Funktionalität der `package` Klasse ist nun in drei Klassen unterteilt:

- `package_raw`
  Repräsentiert ein Paket vom Server. Besitzt die `store`-Methode, um das Paket in der Datenbank zu speichern.
  
- `package`
  Repräsentiert ein in der Datenbank gespeichertes Paket. Die `delete` Methode löscht das Paket und alle Versionen dieses Pakets aus der Datenbank.
  
- `package_version`
  Repräsentiert eine in der Datenbank gespeicherte Version eines Pakets.

2023-07-11 09:01 UTC, MHajoha approved these changes
10/10 Refactoring

![grafik](https://github.com/questionpy-org/moodle-qtype_questionpy/assets/29020266/d35e4a90-f6e1-4ef3-b543-7be0889d10e1)

2023-07-11 09:01 UTC, MHajoha commented on classes/package/package.php
> +        ->alias("hash", "hash")
`package` hat keinen `hash`, oder?

2023-07-11 09:01 UTC, MHajoha commented on classes/package/package.php
> + *
Vielleicht noch die PHPdocs der Klassen konkretisieren?

2023-07-11 09:13 UTC, MHajoha requested changes
Beim zweiten Review passt man besser auf :sweat_smile: Immernoch 9/10

Hast du in IDEA das "PHP language level" auf 7.4 gesetzt? Dann müsste er dir die Sachen vorschlagen. Wir hatten meine ich auch mal überlegt, ob wir getrost für 8.0 (ist ab Moodle 4.2 Minimum) schreiben können, haben aber glaube ich nichts entschieden? @MartinGauk

2023-07-11 09:13 UTC, MHajoha commented on classes/package/package_base.php
> +    protected $shortname;
Die Properties (also auch alle anderen) typisieren.

```suggestion
    /** @var string package shortname */
    protected string $shortname;
```

2023-07-11 09:13 UTC, MHajoha commented on classes/package/package_base.php
> +                                array  $tags = null) {
```suggestion
    public function __construct(string $shortname, string $namespace, array $name, string $type,
                                ?string $author = null, ?string $url = null, ?array $languages = null,
                                ?array  $description = null, ?string $icon = null, ?string $license = null,
                                ?array  $tags = null) {
```

Bitte auch bei den Properties dann benutzen. Im PHPdoc muss es leider `|null` bleiben, da werden die `?`s nicht verstanden.

2023-07-18 12:36 UTC, alexanderschmitz approved these changes

2023-07-20 10:02 UTC, MartinGauk approved these changes

2023-07-20 10:03 UTC, merged