Feature/4/capabilities
questionpy-org/moodle-qtype_questionpy pull request #6
Opened 2022-07-05 17:09 UTC by alexanderschmitz

- settings.php mit den Feldern für die Admin settings. Bei Kleinigkeiten war ich mir nicht sicher wie:
  - ob Uploadsize int oder float sein soll
- capability für upload feature vorbereitet

2022-07-06 09:04 UTC, MartinGauk requested changes

2022-07-06 09:04 UTC, MartinGauk commented on db/access.php
> +    'qtype/questionpy:uploadfiles' => [
Ich würde hier noch genauer schreiben 'qtype/questionpy:uploadpackages'.

2022-07-06 09:04 UTC, MartinGauk commented on edit_questionpy_form.php
> +defined('MOODLE_INTERNAL') || die;
Beschwert sich nicht der Codechecker darüber?
Unexpected MOODLE_INTERNAL check. No side effects or multiple artifacts detected.

2022-07-06 09:04 UTC, MartinGauk commented on settings.php
> +        'qtype_questionpy/applicationserver_url',
Ich würde nur 'qtype_questionpy/server_url' schreiben. Auch unten bei pasword.

2022-07-06 09:04 UTC, MartinGauk commented on settings.php
> +        'qtype_questionpy/applicationserver_maxservertimeout',
Ich würde hier nur 'qtype_questionpy/server_timeout' schreiben. Entsprechend auch im lang_string.

2022-07-06 09:04 UTC, MartinGauk commented on settings.php
> +        'qtype_questionpy/applicationserver_maxquestionsize',
Auch hier würde ich den Namen kürzen und präziser von 'qtype_questionpy/max_package_size_kb' schreiben.

2022-07-06 09:04 UTC, MartinGauk commented on question.php
> +
Das würde ich hier nicht speichern. Wenn wir die doch irgendwann mal hier bräuchten, kann das ja wieder hinzugefügt werden.

2022-07-07 06:07 UTC, alexanderschmitz commented on edit_questionpy_form.php
> +defined('MOODLE_INTERNAL') || die;
Doch der beschwert sich, aber ich dachte das gehört trotzdem dahin. Vor allem weil andere question types das auch in ihrer form haben.

2022-07-07 09:33 UTC, MartinGauk approved these changes

2022-07-07 09:33 UTC, merged