Feat/reactive package container
questionpy-org/moodle-qtype_questionpy pull request #63
Opened 2023-10-12 12:10 UTC by janbritz

Reference #62.

Dieser PR bereitet den reaktiven Package-Container vor.

Die Pakete werden nun mit Hilfe der Moodle-eigenen _reactive library_ asynchron gerendert.
![image](https://github.com/questionpy-org/moodle-qtype_questionpy/assets/43270252/264dc9bd-4834-4cdd-bf93-015ec48d285a)
![image](https://github.com/questionpy-org/moodle-qtype_questionpy/assets/43270252/80d55387-0a38-463f-91f9-de796367fb8b)
Dabei wird zunächst serverseitig ein `state` erstellt, welcher nach der Erstellung dem Package-Container übergeben wird. Dieser iteriert dann über alle verfügbaren Pakete im `state` und rendert sie.
Das Modifizieren des `state` hat leider noch nicht fehlerfrei funktioniert, weshalb das erst in einem nachfolgenden PR hinzugefügt wird.

2023-10-12 16:28 UTC, MHajoha requested changes, later dismissed

2023-10-12 16:28 UTC, MHajoha commented on classes/external/init_packages.php
> +class init_packages extends external_api {
Mit 4.2 geht das kaputt, siehe <https://github.com/questionpy-org/moodle-qtype_questionpy/commit/0d28212e3a283e8f8961e3e21e592625008f8aff>. Müsste hier auch rein.

2023-10-12 16:28 UTC, MHajoha commented on styles.css
> +    width: var(--qpy-card-width);
Ist hier doppelt gemoppelt, oder? Ohne das `width` wächst die `.qpy-card`, um den ganzen `.qpy-reactive-container` zu füllen, das müsste aufs gleiche hinaus kommen und braucht keine Variable.

2023-10-12 16:28 UTC, MHajoha commented on amd/src/container_component.js
> +            }).catch();
Tut es das nicht auch ohne `return null` und leeres `.catch()`?

```suggestion
            Templates.renderForPromise('qtype_questionpy/package/package_selection', {
                "namespace": packageData.namespace,
                "name": packageData.name,
                "description": packageData.description,
                "icon": packageData.icon,
                "selected": false,
                "versions": packageData.versions,
                "url": packageData.url
            }).then(({html, js}) => {
                Templates.appendNodeContents(this.selectors.CONTENTALL, html, js);
            });
```

2023-10-12 16:28 UTC, MHajoha commented on amd/src/container_component.js
> +        const packages = JSON.parse(JSON.stringify(state.packages));
`JSON.parse(JSON.stringify(`?

2023-10-12 16:28 UTC, MHajoha commented on amd/src/container_component.js
> +        this.getElement(this.selectors.LOADINGINDICATOR).classList.add('d-none');
Für die Nutzerfreundlichkeit würde ich hier die Reihenfolge etwas ändern:
* Erst den String holen und die Pakete rendern (hier könnte dir [`Promise.all`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) helfen)
* Erst dann synchron the DOM verändern

Dann gibt es nur eine sichtbare Änderung statt mehrerer

2023-11-03 16:19 UTC, MartinGauk submitted a review, later dismissed
Ich würde diesen PR gerne pausieren und wir sollten versuchen die Arbeit in mehr Teilaufgaben zu trennen. Ich habe daher Issue #68 erstellt und würde dich bitten das zunächst zu bearbeiten.
Im Anschluss sollten wir uns überlegen, was eigentlich alles Teil des States sein sollte.

2023-11-03 16:19 UTC, MartinGauk commented on classes/external/init_packages.php
> +        $packages = package::get_records();
Das skaliert nicht gut, immer alle Pakete zu holen.

2024-01-24 15:03 UTC, janbritz commented on styles.css
> +    width: var(--qpy-card-width);
Wenn ein Paket ausgewählt wurde, existiert der Container nicht mehr.

2024-02-06 09:46 UTC, larsbonczek requested changes

2024-02-06 09:46 UTC, larsbonczek commented on amd/src/package_search/reactive.js
> +        const noData = {
Ich frage mich, ob du vielleicht Probleme bekommst, wenn du die Referenz auf dieses Objekt unten im State viermal verwendest. Du willst ja nicht, dass sich `count` bei allen Tabs verändert, wenn du den Wert bei einem Tab änderst.

Kann gut sein, dass das nicht passiert, weil der State nochmal geklont wird oder so. Aber probier es besser mal aus, oder verzichte auf die Variable und dupliziere den Code einfach viermal.

2024-02-06 09:46 UTC, larsbonczek commented on amd/src/package_search/mutations.js
> +        return Ajax.call(methods);
Vielleicht wäre es besser, die (initiale) Suche in nur einem Request durchzuführen, und die Ergebnisse nach Kategorie zu gruppieren. Dann muss nur eine Anfrage an die Datenbank gemacht werden statt vier. Lass uns mal darüber reden.

2024-02-06 09:46 UTC, larsbonczek commented on amd/src/package_search/mutations.js
> +            clonedArgs = {...args};
Ist es nötig, die Argumente neu zu klonen? Du überschreibst doch das category-Feld in jeder Iteration.

2024-02-06 09:46 UTC, larsbonczek commented on amd/src/package_search/mutations.js
> +            order: args.order || state.general.order,
Werden `state.general.query` und die anderen State-Felder auch irgendwo gesetzt? Müsste das nicht bei jeder neuen Suche passieren?

2024-02-06 09:46 UTC, larsbonczek commented on templates/package_search/area.mustache
> +        <input type="text" class="form-control" data-for="search-bar" aria-label="{{#str}}search_bar_label_aria, qtype_questionpy{{/str}}" placeholder="{{#str}}search_bar, qtype_questionpy{{/str}}">
Verwende den helper {{#cleanstr}}, wenn du strings in HTML-Attributen verwendest. Der escaped unter anderem Anführungsstriche. Die würden sonst dein HTML kaputt machen. #cleanstr funktioniert ansonsten genau wie #str.

Das gilt natürlich auch für alle anderen Stellen.

2024-02-06 09:46 UTC, larsbonczek commented on lang/en/qtype_questionpy.php
> +$string['search_mine_header'] = 'Mine ({$a})';
Language strings werden in Moodle nach den gleichen Regeln benannt wie Variablen:
https://moodledev.io/general/development/policies/codingstyle#variables

Und normalerweise werden die strings in dieser Datei dann alphabetisch sortiert.

2024-02-06 09:46 UTC, larsbonczek commented on amd/src/package_search/components/search_bar.js
> +        this.searchPackages = debounce((event) => this._searchPackages(event), 300);
Mache das bitte einfach zu einer normalen Funktion. So ist es etwas verwirrend.

Den Code von _searchPackages kannst du dann auch einfach da einfügen. Dafür braucht es keine extra Funktion.

2024-02-06 09:46 UTC, larsbonczek commented on amd/src/package_search/components/container.js
> +        await templates.prefetchTemplates([this.packageTemplate]);
Hier sollte das await entfernt werden, damit das Template im Hintergrund geladen wird und der Reactive UI Code nicht darauf warten muss

2024-02-06 09:46 UTC, larsbonczek commented on amd/src/package_search/components/container.js
> +    }
Kann weg?

2024-02-06 09:46 UTC, larsbonczek commented on amd/src/package_search/components/container.js
> +        this.getElement(this.selectors.LOADING_INDICATOR).style.visibility = loading ? "visible" : "hidden";
Der visibility style ändert nur die Sichtbarkeit eines Elementes. Es nimmt aber weiterhin Platz auf der Seite weg, auch wenn es unsichtbar ist. Meistens ist das nicht gewollt. Verwende deshalb besser display.

Generell würde ich es aber bevorzugen, wenn dieses Element durch eine Klasse versteckt wird. Du könntest zum Beispiel dem Container eine "loading"-Klasse geben und den loading indicator per Stylesheet verstecken, wenn diese Klasse nicht vorhanden ist.

2024-02-06 09:46 UTC, larsbonczek commented on styles.css
> +    margin: 2px;
Bitte nach Möglichkeit immer relative Einheiten verwenden (rem). Teste die styles auch für mobile Endgeräte.

2024-02-06 14:32 UTC, janbritz commented on templates/package_search/area.mustache
> +        <input type="text" class="form-control" data-for="search-bar" aria-label="{{#str}}search_bar_label_aria, qtype_questionpy{{/str}}" placeholder="{{#str}}search_bar, qtype_questionpy{{/str}}">
Ah, gut zu wissen! In den Docs ist dazu mal wieder leider nichts zu finden..

2024-02-08 10:57 UTC, janbritz commented on amd/src/package_search/mutations.js
> +        return Ajax.call(methods);
Gerne, die Suche selbst wird zu einem Request gebündelt, der Service wird allerdings bis zu viermal ausgeführt. Eine Änderung würde ich erst in einem anderen PR sehen.

2024-02-08 11:01 UTC, janbritz commented on lang/en/qtype_questionpy.php
> +$string['search_mine_header'] = 'Mine ({$a})';
Ich habe dazu mal [ein Issue](https://github.com/questionpy-org/moodle-qtype_questionpy/issues/95) erstellt.

2024-02-09 11:35 UTC, larsbonczek requested changes

2024-02-09 11:35 UTC, larsbonczek commented on templates/package_search/area.mustache
> +                <button class="nav-link" data-for="mine-header" id="qpy-mine-header-{{uniqid}}" data-toggle="tab" data-target="#qpy-mine-content-{{uniqid}}" type="button" role="tab" aria-controls="qp
cleanstr muss nur in HTML-Attributen verwendet werden.

2024-02-14 10:55 UTC, larsbonczek approved these changes

2024-02-15 13:19 UTC, merged